# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  up:
    cmds:
      - kind create cluster -n kind-home
  down:
    cmds:
      - kind delete cluster -n kind-home

  cortex:
    dir: ./terraform/cortex
    cmds:
      - echo $KUBECONFIG
      - terraform init
      - terraform apply -auto-approve
